version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: invoice
      MYSQL_USER: invoice 
      MYSQL_PASSWORD: invoicepassword
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3307:3306"
  app:
    build: 
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
volumes:
  db:
